### ISSUE TITLE
[Feature] Prompt to add Nerd font

### ISSUE THREAD

**Issue by niksingh710** [marty-oehme/bemoji#10]
As the emoji Db is mere simple .txt 
we can prompt the user at first start if he wants to have the Nerd Font [Cheat Sheet](https://www.nerdfonts.com/cheat-sheet) database appended to it to have access to much more glyphs.

**Comment by marty-oehme** [comment]
Do you mean as another parameter essentially for the `-D` option, so that instead of just `-D emoji` or `math` we could also do `nerdfont`?

I am not exactly familiar with how the nerdfont cheatsheet keeps its entries, is there a single page text file with all the entries listed that we could curl? 

Then I believe it should not be too hard to implement. 
Also, last question, the emojis gotten from this page would presumably only work with fonts that have the nerdfont glyphs enabled, correct?

**Comment by niksingh710** [comment]
yep to get the nerd font glyphs to work the user is required to have a nerd font ttf|otf file installed in the system.

I am unable to find nerdfont cheat sheet in a text file on their website they have it. 

i found a new addition that is also helpful [Unicode](https://gist.github.com/jpassaro/bf400b0410810a071a7fb3509ef6c2c3)

**Comment by niksingh710** [comment]
[Nerd-font](https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/css/nerd-fonts-generated.css)

have to figure out how to get the corresponding icons with them.

**Comment by marty-oehme** [comment]
I see, yes for the nerdfont we would need a way to get both the glyph and the description together.

The unicode sheet is actually a really good idea and easier to implement, maybe you can open a new issue with that one and we could probably get it added relatively painlessly - seems 

In general I am hesitant of putting *too* many downloaders in the main file since I don't want to add too much code complication into the file that does not directly have to do with actual emoji typing/copying. But perhaps if we get more added, we could split it into its own little script that then gets called by the main program on first run. I'll have a think about it.

**Comment by niksingh710** [comment]
> In general I am hesitant of putting _too_ many downloaders in the main file since I don't want to add too much code complication into the file that does not directly have to do with actual emoji typing/copying. But perhaps if we get more added, we could split it into its own little script that then gets called by the main program on first run. I'll have a think about it.

Yeah having separate files will be nice as the main motive is only emojis. (unicode+nerdfont) are additional stuff based on user choice if the user wants to add them.
we can have separate .txt file to store Unicode and nerd font.

For Unicode, i have created a new issue [#11](https://github.com/marty-oehme/bemoji/issues/11)
