### ISSUE TITLE
[Feature] Unicode addition in the db

### ISSUE THREAD

**Issue by niksingh710** [marty-oehme/bemoji#11]
A new argument flag that gives the user a choice to download Unicode characters dictionary from the source ([This one can be used](https://gist.github.com/jpassaro/bf400b0410810a071a7fb3509ef6c2c3)).

Having emoji and Unicode together can have conflict so we can have different search patterns to make it easier

e.g normal search results in emoji on top 
searching with `u:<name>` should result in Unicode on top 
This can be achieved by adding `u:` at the start of the Unicode description .txt and for bemenu we can sed it and remove it when the user invokes it.

**Comment by marty-oehme** [comment]
Thanks for separating this one. Unicode and emoji are conflicting in instances because the emoji set that is automatically downloaded by this program is also already part of the unicode standard.

I'll unfortunately basically have not time to devote to this again for another week or two. 
Maybe you can see if you find the unicode blocks of interest - the current downloaders take their lists from https://unicode.org/Public/ - and already wrangle it into shape with a sed or cut expression similar to [this](https://github.com/marty-oehme/bemoji/blob/main/bemoji#L93) or [this](https://github.com/marty-oehme/bemoji/blob/main/bemoji#L98)?

**Comment by marty-oehme** [comment]
I will close this for now, as I have gone through the unicode set and found out that most symbols are included with the unicode MATH set that we are downloading already.
The unicode blocks in the link above we are missing the most symbols of are:

- cyrillic
- general punctuation
- miscellaneous symbols

While we include either all of the other blocks or most of, such as the geometric shapes and number forms blocks.

I think for most users this should be enough?

If there is still an interest in including additional blocks I think it would be better to open a new issue with the specific blocks/lists of symbols in mind.

We *are* now including a download to the nerd font symbol set that this issue grew out of, however - see the linked issue above.
