### ISSUE TITLE
How to make it work with Clipman

### ISSUE THREAD

**Issue by blogdemoi** [marty-oehme/bemoji#23]
Hi,

How can I make it work with the Clipman clipboard https://docs.xfce.org/panel-plugins/xfce4-clipman-plugin/start ?

Thank you.

**Comment by marty-oehme** [comment]
Hi @blogdemoi ,

sorry for keeping you hanging so long! 

I am not immediately familiar with this 'Clipman' tool, though it seems to be a clipboard manager which is mostly there to keep a recent history of your copied selections?

If so, it should work more or less automatically. If anything is copied into one of the clipboard the tool should pick it up and show it as an entry.

You will however still need one of `xclip` or `xsel` installed on your system since they are the programs that get the selection *into* the clipboard in the first place.

Does this help with your question?
Let me know if you intended something else instead.

**Comment by marty-oehme** [comment]
If anything new pops up let me know, but for now I would consider this issue closed.
