### ISSUE TITLE
Release with fuzzel

### ISSUE THREAD

**Issue by cloudlena** [marty-oehme/bemoji#26]
Could we get an official release with the new fuzzel picker included? That would be awesome :smiley_cat:

**Comment by marty-oehme** [comment]
Hi @cloudlena , just wanted to drop by quickly to let you know I am not ignoring the issues - but still in a busy phase currently.

Have been meaning to release a new official version with all the pickers and improvements for a while now but would like to do so when I have a little more time to dedicate to it. Perhaps aiming for end of the month or so would be a reasonable expectation that we can aim for :slightly_smiling_face:

**Comment by kulothunganug** [comment]
`bemoji-git` (AUR) helped me, as the project is just a script, no need of compilation, works flawlessly with `fuzzel`.
Thanks for the work 😃

**Comment by marty-oehme** [comment]
Hey, took a little longer of course but the new version is now released and should hopefully be available soon in the AUR as well.

Also @kulothunganug you're right that the git version is equally usable for the most part. And thank you too!
Happy to hear it works well with fuzzel since I don't regularly test it this is good to know :smiley:

**Comment by cloudlena** [comment]
Amazing. Thanks, @marty-oehme!
