### ISSUE TITLE
[Feature] Allow selection of launcher

### ISSUE THREAD

**Issue by justin8** [marty-oehme/bemoji#40]
Currently there is a default list of launchers that are supported, and the first available one gets run. I had recently swapped from wofi to rofi and bemoji picked the wrong one as it was higher in it's order and currently there's no way to pick without uninstalling the tools you do not want bemoji to use.

**Comment by marty-oehme** [comment]
You are correct that selection of a picker is currently a little iffy and definitely due for some rethinking (#22). 

However, you can [manually override](https://github.com/marty-oehme/bemoji?tab=readme-ov-file#using-a-custom-tool-for-picking-clipping-typing) the picker selection with the env var `BEMOJI_PICKER_CMD`, so for example `BEMOJI_PICKER_CMD="rofi -dmenu" bemoji` would populate rofi instead of wofi with emojis even with both installed.

**Comment by justin8** [comment]
Ahh, that’s good to know, thanks!

**Comment by marty-oehme** [comment]
If that answers the specific issue I'll close here so we can follow picker selection improvements in #22 instead.
